---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


```{r}
library(tidyverse)
library(NSGA2)
library(randomForest)

#generate data
set.seed(124)
X <- matrix(runif(160), ncol = 4) %>% as.data.frame() 
Y <- data.frame(Y1 = 2*X[,1] + X[,2]^2 + X[,1]*X[,4] + rnorm(NROW(X), sd=0.5),
                Y2 = 1.25*X[,2] + X[,4]^3 + X[,1]*X[,2] + rnorm(NROW(X), sd=0.5))

#fit function
f1 <- randomForest(x=X, y=Y[,1])
f2 <- randomForest(x=X, y=Y[,2])
f3 <- function(X) 1.25*X[,2] + X[,4]^3 + X[,1]*X[,2]

#proceed to the research
res = NSGA(X, 
           ff = list(list(f = f1, sens = "min"), list(f = f2, sens = "min")),
           crossing_over_size = 2,
           freq_mutation = c(0.4, 0.4, 0.4, 0.4), B=10)

plot(res$Y[,1:2])
res$Pt

```

